from pythonosc import udp_client
import time
import os

time.sleep(15)

# Set up OSC
local_ip = "192.168.0.19" # Your computers local IP
port = 9000 # VR Chat port, 9000 is the default
osc_client = udp_client.SimpleUDPClient(local_ip, port)
osc_client.send_message("/chatbox/input", ["Positioning...", True])

################################################################################################
# "The Black Cat" Positions: "Downstairs Bar" "Upstairs Bar" "Front Desk" "Downstairs Bar Back"
world = "The Black Cat"
position = "Downstairs Bar"
################################################################################################

if world == "The Black Cat":
    if position == "Downstairs Bar":
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(5.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(4.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(2.9)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.2)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(0.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.2)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.33)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/MoveForward", 0)
    elif position == "Upstairs Bar":
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(5.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.45)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(4.3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.45)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3.55)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.45)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.7)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(4)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.8)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.34)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3.4)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.5)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.43)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/MoveForward", 0)
    elif position == "Front Desk":
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.38)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.45)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1.4)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.48)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/MoveForward", 0)
    elif position == "Downstairs Bar Back":
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(5.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(4.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.3)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(3.4)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.15)
        osc_client.send_message("/input/LookLeft", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.15)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.15)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(1)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookRight", 1)
        time.sleep(0.2)
        osc_client.send_message("/input/LookRight", 0)
        osc_client.send_message("/input/MoveForward", 1)
        time.sleep(0.5)
        osc_client.send_message("/input/MoveForward", 0)
        osc_client.send_message("/input/LookLeft", 1)
        time.sleep(0.4)
        osc_client.send_message("/input/LookLeft", 0)

# Start the main.py program
osc_client.send_message("/chatbox/input", ["System Starting...", True])
os.system('cd F:/USB/vr-ai-chatbot-main')
os.system('python main.py')