name: Black Code Formatting

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  black:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
        
    - name: Check code formatting with black
      run: |
        black --check --diff .
