name: Test Coverage

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        # Install project dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
        
    - name: Run tests with coverage
      run: |
        # Run coverage on smoke test if it exists, or skip if no tests
        if [ -f smoke_test.py ]; then
          coverage run -m pytest smoke_test.py --tb=short || coverage run smoke_test.py || echo "No tests to run"
        else
          echo "No test files found"
        fi
        
    - name: Generate coverage report
      run: |
        coverage report -m || echo "No coverage data available"
        
    - name: Generate coverage XML
      run: |
        coverage xml || echo "No coverage data available"
