name: isort Import Sorting

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  isort:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install isort
      run: |
        python -m pip install --upgrade pip
        pip install isort
        
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
