name: MyPy Type Checking

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  mypy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        # Install project dependencies for better type checking
        if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
        
    - name: Run mypy type checking
      run: |
        # Run mypy with lenient settings initially
        mypy --ignore-missing-imports --no-strict-optional --allow-untyped-calls --allow-untyped-defs . || true
