name: Security Audit (pip-audit)

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:
  schedule:
    # Run weekly on Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit
        
    - name: Run pip-audit on requirements.txt
      run: |
        # Audit the requirements file for known vulnerabilities
        pip-audit -r requirements.txt || true
