name: Pydocstyle Docstring Style

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install pydocstyle
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle
        
    - name: Run pydocstyle
      run: |
        # Run pydocstyle with lenient settings initially
        pydocstyle --count . || true
