name: Pylint Code Quality

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]
  merge_group:

jobs:
  pylint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies for better analysis
        if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
        
    - name: Run pylint
      run: |
        # Run pylint on all Python files, allowing the job to continue even with issues
        pylint $(find . -name "*.py" -not -path "./.git/*" -not -path "./__pycache__/*") --exit-zero || true
